BEGIN;

-- ============================================================================
-- Curriculum Parser Database Schema
-- ============================================================================
-- This schema matches SQLAlchemy models in app/models.py
-- All table names use plural form (e.g., lecturers, disciplines, etc.)
-- ============================================================================

-- Lookup tables (GENERATED BY DEFAULT allows manual ID insertion for ETL)
CREATE TABLE IF NOT EXISTS activity_types (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS control_forms (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS lecturers (
    id            INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20) NOT NULL CHECK (role IN ('admin','lecturer','viewer'))
);

-- Students table
CREATE TABLE IF NOT EXISTS students (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(120) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin','lecturer','viewer'))
);

CREATE INDEX IF NOT EXISTS idx_students_email 
    ON students(email);

CREATE TABLE IF NOT EXISTS disciplines (
    id           INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name         VARCHAR(200) NOT NULL,
    course       INT NOT NULL CHECK (course > 0),
    ects_credits NUMERIC(4,1) NOT NULL CHECK (ects_credits >= 0),
    lecturer_id  INT NOT NULL,
    CONSTRAINT fk_discipline_lecturer FOREIGN KEY (lecturer_id)
        REFERENCES lecturers (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS semesters (
    id             INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    number         INT NOT NULL CHECK (number > 0),
    weeks          INT NOT NULL CHECK (weeks > 0),
    hours_per_week INT NOT NULL CHECK (hours_per_week >= 0)
);

CREATE TABLE IF NOT EXISTS sections (
    id            INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name          VARCHAR(200) NOT NULL,
    discipline_id INT NOT NULL,
    semester_id   INT,
    CONSTRAINT fk_section_discipline FOREIGN KEY (discipline_id)
        REFERENCES disciplines (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_section_semester FOREIGN KEY (semester_id)
        REFERENCES semesters (id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS themes (
    id          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        VARCHAR(300) NOT NULL,
    section_id  INT NOT NULL,
    total_hours INT NOT NULL DEFAULT 0 CHECK (total_hours >= 0),
    CONSTRAINT fk_theme_section FOREIGN KEY (section_id)
        REFERENCES sections (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS activities (
    id               INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name             VARCHAR(300),
    type_id          INT,
    hours            INT NOT NULL DEFAULT 0 CHECK (hours >= 0),
    theme_id         INT NOT NULL,
    control_form_id  INT,
    CONSTRAINT fk_activity_type FOREIGN KEY (type_id)
        REFERENCES activity_types (id) ON UPDATE CASCADE,
    CONSTRAINT fk_activity_theme FOREIGN KEY (theme_id)
        REFERENCES themes (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_activity_control FOREIGN KEY (control_form_id)
        REFERENCES control_forms (id) ON UPDATE CASCADE
);

-- Check if enum type 'weekday' exists before creating
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'weekday') THEN
        CREATE TYPE weekday AS ENUM (
            'monday','tuesday','wednesday','thursday','friday'
        );
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS schedule (
    id          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    day         weekday NOT NULL,
    pair_number INT NOT NULL CHECK (pair_number > 0),
    room        VARCHAR(20),
    activity_id INT NOT NULL UNIQUE,
    CONSTRAINT fk_schedule_activity FOREIGN KEY (activity_id)
        REFERENCES activities (id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ETL Error logging table
CREATE TABLE IF NOT EXISTS etl_errors (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    
    -- Timestamp of error occurrence
    timestamp TIMESTAMP NOT NULL DEFAULT NOW(),
    
    -- Error classification
    error_type VARCHAR(50) NOT NULL CHECK (
        error_type IN ('validation', 'database', 'parse', 'constraint', 'unknown')
    ),
    severity VARCHAR(20) NOT NULL CHECK (
        severity IN ('error', 'warning', 'info')
    ),
    
    -- Context information
    row_number INT,
    field_name VARCHAR(100),
    
    -- Error details
    message TEXT NOT NULL,
    source_data TEXT,
    
    -- ETL session tracking
    etl_session_id UUID,
    file_name VARCHAR(255),
    
    -- Additional info
    stack_trace TEXT,
    resolved BOOLEAN DEFAULT FALSE
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- Indexes for etl_errors
CREATE INDEX IF NOT EXISTS idx_etl_errors_timestamp 
    ON etl_errors(timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_etl_errors_session_id 
    ON etl_errors(etl_session_id);

CREATE INDEX IF NOT EXISTS idx_etl_errors_severity 
    ON etl_errors(severity);

-- Indexes for main tables
CREATE INDEX IF NOT EXISTS idx_lecturers_email 
    ON lecturers(email);

CREATE INDEX IF NOT EXISTS idx_disciplines_lecturer_id 
    ON disciplines(lecturer_id);

CREATE INDEX IF NOT EXISTS idx_sections_discipline_id 
    ON sections(discipline_id);

CREATE INDEX IF NOT EXISTS idx_sections_semester_id 
    ON sections(semester_id);

CREATE INDEX IF NOT EXISTS idx_themes_section_id 
    ON themes(section_id);

CREATE INDEX IF NOT EXISTS idx_activities_theme_id 
    ON activities(theme_id);

CREATE INDEX IF NOT EXISTS idx_activities_type_id 
    ON activities(type_id);

CREATE INDEX IF NOT EXISTS idx_activities_control_form_id 
    ON activities(control_form_id);

CREATE INDEX IF NOT EXISTS idx_schedule_activity_id 
    ON schedule(activity_id);

COMMIT;
